//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string p_prodid { get; set; }
        public string p_prodname { get; set; }
        public string p_classid { get; set; }
        public Nullable<bool> p_status { get; set; }
        public Nullable<bool> p_display { get; set; }
        public string p_onshaffdateb { get; set; }
        public string p_onshaffdaten { get; set; }
        public Nullable<int> p_playseq { get; set; }
        public string p_packagetext { get; set; }
        public string p_functiontext { get; set; }
        public Nullable<decimal> p_price { get; set; }
    }
}
